Minimal nix std example
Fails when running on my ArchLinux environment, due to a missing
`PRJ_ROOT` environment variable. When not set;

```console
❯ nix run github:divnix/std -- '//simple/devshell/default:enter'
mkdir: cannot create directory ‘/.std’: Permission denied
error: '#x86_64-linux.simple.devshell.default' is not a valid URL
bash: line 1: /.std/simple/devshell/default/shell-profile/env.bash: No such file or directory
bash: line 1: __devshell-motd: command not found
```

but when set to `$PWD` it works;

```console
❯ export PRJ_ROOT="$PWD"
❯ nix run github:divnix/std -- '//simple/devshell/default:enter'

🔨 Welcome to Simple Test Devshell 🔨

To autocomplete 'std' in bash, zsh, oil: source <(std _carapace)
More shells: https://rsteube.github.io/carapace/carapace/gen/hiddenSubcommand.html

[general commands]

  menu - prints this menu
  std  - A tui for projects that conform to Standard
```

Not sure if this is intentional behaviour of `std` (or maybe
`devshell`)?